// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8NSdzSCgbYzf3xuP96qXpEuemKUM1Y2A',
    appId: '1:359844895870:web:f6461bc6485dbbb1ca4c2f',
    messagingSenderId: '359844895870',
    projectId: 'shakti-924fe',
    authDomain: 'shakti-924fe.firebaseapp.com',
    storageBucket: 'shakti-924fe.appspot.com',
    measurementId: 'G-H2RZXWP7YE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYAq2NDWbwxgXqHA_LAq2n2w0t6FzzaUM',
    appId: '1:359844895870:android:25c65ffd9059f1ceca4c2f',
    messagingSenderId: '359844895870',
    projectId: 'shakti-924fe',
    storageBucket: 'shakti-924fe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxPOjZ9i6mgremRx6pFy3TbdCmiGS1-FE',
    appId: '1:359844895870:ios:e01ed4adaa3cb346ca4c2f',
    messagingSenderId: '359844895870',
    projectId: 'shakti-924fe',
    storageBucket: 'shakti-924fe.appspot.com',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxPOjZ9i6mgremRx6pFy3TbdCmiGS1-FE',
    appId: '1:359844895870:ios:562c8b72fdff9ddfca4c2f',
    messagingSenderId: '359844895870',
    projectId: 'shakti-924fe',
    storageBucket: 'shakti-924fe.appspot.com',
    iosBundleId: 'com.example.flutterApp.RunnerTests',
  );
}
